image: tweag/stack-docker-nix

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

cache:
  paths:
    - .stack
    - .stack-work
    - target

stages:
  - build
  - test

build:
  stage: build
  script:
    - make setup
    - make build

#unit-test:
#  stage: test
#  script:
#    - make test-unit
#
#int-test:
#  stage: test
#  script:
#    - make test-int
#
#e2e-test:
#  stage: test
#  script:
#    - make test-e2e
#

# If you find yourself with a non-sensical build error when you know your project should be building just fine, this fragment should help:
#
#build:
#  stage: build
#  script:
#    # Clear out cache files
#    - rm -rf .stack
#    - rm -rf .stack-work
#    - stack setup --system-ghc
#    - stack install --local-bin-path target --system-ghc