#!/bin/bash


if git --version;
then 
  echo "git installed, ok"
else
  sudo apt update && sudo apt install git
fi

sudo apt update &&  sudo apt install liblzma-dev libpcre3-dev libblas-dev liblapack-dev pkg-config libgsl-dev libbz2-dev


curl -sSL https://get.haskellstack.org/ | sh
stack update
stack upgrade


git clone https://gitlab.iscpif.fr/gargantext/haskell-gargantext.git

cd haskell-gargantext
git clone https://gitlab.iscpif.fr/gargantext/purescript-gargantext

mkdir deps
cd deps
git clone https://gitlab.iscpif.fr/gargantext/clustering-louvain.git
git clone https://github.com/np/servant-job.git
git clone https://github.com/np/patches-map
git clone https://gitlab.com/npouillard/patches-class.git
git clone https://github.com/delanoe/haskell-opaleye
git clone -b next --single-branch https://github.com/delanoe/hsparql
cd ..

stack docker pull
stack --docker setup
stack --docker build
stack --docker install


# Database configuration
# CREATE USER gargantua WITH PASSWORD $(grep DB_PASS gargantext.ini)
# GRANT ALL PRIVILEGES ON DATABASE gargandbV4 to gargantua
