#!/bin/bash

# On Debian:
# sudo apt-get update && sudo apt-get install libpcre3-dev libbz2-dev

curl -sSL https://get.haskellstack.org/ | sh
stack update

git clone ssh://git@gitlab.iscpif.fr:20022/gargantext/haskell-gargantext.git

cd haskell-gargantext

git clone ssh://git@gitlab.iscpif.fr:20022/gargantext/purescript-gargantext

mkdir deps
cd deps
git clone ssh://git@gitlab.iscpif.fr:20022/gargantext/clustering-louvain.git
git clone https://github.com/np/servant-job.git
cd ..

stack setup
stack build
stack install

