name: gargantext
version: '0.1.0.0'
synopsis: Deep (Collaborative) Text mining project
description: Please see README.md
category: Data
author: Gargantext Team
maintainer: team@gargantext.org
copyright:
    - ! 'Copyright: (c) 2017-2018: see git logs and README'
license: BSD3
homepage: https://gargantext.org
ghc-options: -Wall
dependencies:
- extra
- text
library:
  source-dirs: src
  default-extensions: 
  ghc-options:
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-signatures
    #  - -Werror
  exposed-modules:
  - Gargantext
  - Gargantext.Database
  - Gargantext.Database.Instances
  - Gargantext.Database.Ngram
  - Gargantext.Database.Node
  - Gargantext.Database.Facet
  - Gargantext.Database.NodeNgram
  - Gargantext.Database.NodeNgramNgram
  - Gargantext.Database.NodeNode
  - Gargantext.Database.NodeNodeNgram
  - Gargantext.Database.Utils
  - Gargantext.Database.User
  - Gargantext.Graph.Utils
  - Gargantext.Graph.Distances.Conditional
  - Gargantext.Graph.Distances.Distributional
  - Gargantext.Graph.Distances.Matrice
  - Gargantext.Ngrams
  - Gargantext.Ngrams.Analysis
  - Gargantext.Ngrams.TFICF
  - Gargantext.Ngrams.Letters
  - Gargantext.Ngrams.CoreNLP
  - Gargantext.Ngrams.Parser
  - Gargantext.Ngrams.Lang.En
  - Gargantext.Ngrams.Lang.Fr
  - Gargantext.Ngrams.Metrics
  - Gargantext.Ngrams.TextMining
  - Gargantext.Ngrams.Occurrences
  - Gargantext.Parsers
  - Gargantext.Parsers.WOS
  - Gargantext.Parsers.Date
  - Gargantext.Prelude
  - Gargantext.API
  - Gargantext.API.Auth
  - Gargantext.Types
  - Gargantext.Types.Main
  - Gargantext.Types.Node
  - Gargantext.Utils.DateUtils
  - Gargantext.Utils.Prefix
  dependencies:
  - QuickCheck
  - accelerate
  - aeson
  - aeson-lens
  - aeson-pretty
  - async
  - attoparsec
  - base >=4.7 && <5
  - base16-bytestring
  - bytestring
  - case-insensitive
  - conduit
  - conduit-extra
  - containers
  - contravariant
  - data-time-segment
  - directory
  - duckling
  - filepath
  - fclabels
  - fast-logger
    #  - haskell-gi-base
  - http-conduit
  - http-api-data
  - http-types
  - hxt
  - hlcm
  - ini
  - jose-jwt
  - lens
  - logging-effect
  - matrix
  - monad-logger
  - mtl
  - natural-transformation
  - opaleye
  - parsec
  - path
  - path-io
  - postgresql-simple
  - pretty
  - product-profunctors
  - profunctors
  - protolude
  - pureMD5
  - regex-compat
  - resourcet
  - safe
  - semigroups
  - servant
  - servant-auth
  - servant-client
  - servant-mock
  - servant-multipart
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - servant-static-th
  - split
  - stemmer
  - string-conversions
  - swagger2
  - tagsoup
  - text-metrics
  - time
  - time-locale-compat
  - timezone-series
  - transformers
  - transformers-base
  - unordered-containers
  - uuid
  - vector
  - wai
  - wai-cors
  - wai-extra
  - warp
  - yaml
  - zip
  - zlib
#  - utc

executable:
  main: Main.hs
  source-dirs:      app
  ghc-options:
    #- -threaded
  - -rtsopts
    # - -with-rtsopts=-N
  - -O2
  - -Wmissing-signatures
  dependencies:
    - base
    - gargantext
    - ini
    - optparse-generic
    - unordered-containers

tests:
  garg-test:
    main: Main.hs
    source-dirs: src-test
    default-extensions: 
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - gargantext
    - hspec
    - QuickCheck
    - quickcheck-instances 
    - time
    - parsec
    - duckling
    - text
  garg-doctest:
    main: Main.hs
    source-dirs: src-doctest
    ghc-options:
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wmissing-signatures
    dependencies:
    - doctest
    - Glob
    - QuickCheck
    - base
    - gargantext
