name: gargantext
version: '4.0.0.2'
synopsis: Search, map, share
description: Please see README.md
category: Data
author: Gargantext Team
maintainer: team@gargantext.org
copyright:
    - ! 'Copyright: (c) 2017-2018: see git logs and README'
license: BSD3
homepage: https://gargantext.org
ghc-options: -Wall
dependencies:
- extra
- text
library:
  source-dirs: src
  ghc-options:
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wmissing-signatures
  - -Wunused-binds
  - -Wunused-imports
  - -Werror
  exposed-modules:
  - Gargantext
  - Gargantext.API
  - Gargantext.API.Auth
  - Gargantext.API.Count
  - Gargantext.API.FrontEnd
  - Gargantext.API.Orchestrator
  - Gargantext.API.Search
  - Gargantext.API.Settings
  - Gargantext.Core
  - Gargantext.Core.Types
  - Gargantext.Core.Types.Main
  - Gargantext.Core.Utils.Prefix
  - Gargantext.Database
  - Gargantext.Database.Bashql
  - Gargantext.Database.Node.Document.Insert
  - Gargantext.Database.Node.Document.Add
  - Gargantext.Database.Node.Contact
  - Gargantext.Database.Types.Node
  - Gargantext.Database.User
  - Gargantext.Database.Cooc
  - Gargantext.Database.Tree
  - Gargantext.Prelude
  - Gargantext.Text
  - Gargantext.Text.Context
  - Gargantext.Text.Examples
  - Gargantext.Text.List.CSV
  - Gargantext.Text.Metrics
  - Gargantext.Text.Metrics.CharByChar
  - Gargantext.Text.Metrics.Count
  - Gargantext.Text.Parsers.CSV
  - Gargantext.Text.Parsers.Date
  - Gargantext.Text.Parsers.Wikimedia
  - Gargantext.Text.Parsers.WOS
  - Gargantext.Text.Search
  - Gargantext.Text.Terms
  - Gargantext.Text.Terms.Stop
  - Gargantext.Text.Terms.Mono
  - Gargantext.Text.Terms.Multi.Lang.En
  - Gargantext.Text.Terms.Multi.Lang.Fr
  - Gargantext.Text.Terms.Multi.RAKE
  - Gargantext.Text.Terms.WithList
  - Gargantext.Text.Flow
  - Gargantext.Viz.Graph
  - Gargantext.Viz.Graph.Distances.Matrice
  - Gargantext.Viz.Graph.Index
  dependencies:
  - QuickCheck
  - accelerate
  - aeson
  - aeson-lens
  - aeson-pretty
  - async
  - attoparsec
  - base >=4.7 && <5
  - base16-bytestring
  - blaze-html
  - bytestring
  - case-insensitive
  - cassava
  #- charsetdetect-ae  # detect charset
  - clustering-louvain
  - conduit
  - conduit-extra
  - containers
  - contravariant
  - data-time-segment
  - directory
  - duckling
  - exceptions
  - filepath
  - fullstop
  - fclabels
  - fast-logger
  - full-text-search
  - http-client
  - http-client-tls
  - http-conduit
  - http-api-data
  - http-types
  - hxt
  - hlcm
  - ini
  - insert-ordered-containers
  - jose-jwt
    #  - kmeans-vector
  - KMP
  - lens
  - located-base
  - logging-effect
  - matrix
  - monad-logger
  - mtl
  - natural-transformation
  - opaleye
  - pandoc
  - parsec
  - patches-class
  - patches-map
  - path
  - path-io
  - postgresql-simple
  - pretty-simple
  - probability
  - product-profunctors
  - profunctors
  - protolude
  - pureMD5
  - SHA
  - rake
  - regex-compat
  - resourcet
  - safe
  - semigroups
  - servant
  - servant-auth
  - servant-blaze
  - servant-client
  - servant-job
  - servant-mock
  - servant-multipart
  - servant-server
  - servant-swagger
  - servant-swagger-ui
  - servant-static-th
  - split
  - stemmer
  - string-conversions
  - swagger2
  - tagsoup
  - text-metrics
  - time
  - time-locale-compat
  - timezone-series
  - transformers
  - transformers-base
  - unordered-containers
  - uuid
  - vector
  - wai
  - wai-cors
  - wai-extra
  - warp
  - xml-conduit
  - xml-types
  - yaml
  - zip
  - zlib
#  - utc

executables:
  gargantext-server:
    main: Main.hs
    source-dirs: bin/gargantext-server
    ghc-options:
    - -O2
    - -Wcompat
    - -Wmissing-signatures
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
      - base
      - containers
      - gargantext
      - vector
      - cassava
      - ini
      - optparse-generic
      - unordered-containers
      - full-text-search

  gargantext-cli:
    main: Main.hs
    source-dirs: bin/gargantext-cli
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wmissing-signatures
    dependencies:
      - aeson
      - async
      - base
      - bytestring
      - containers
      - gargantext
      - vector
      - cassava
      - ini
      - optparse-generic
      - split
      - unordered-containers
      - full-text-search

tests:
#   garg-test:
#     main: Main.hs
#     source-dirs: src-test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - base
#     - gargantext
#     - hspec
#     - QuickCheck
#     - quickcheck-instances 
#     - time
#     - parsec
#     - duckling
#     - text
  garg-doctest:
    main: Main.hs
    source-dirs: src-doctest
    ghc-options:
    - -O2
    - -Wcompat
    - -Wmissing-signatures
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - Glob
    - QuickCheck
    - base
    - gargantext
