resolver: lts-14.16
flags: {}
extra-package-dbs: []
packages:
- .


docker:
  enable: true
  repo: 'cgenie/stack-build:lts-14.6-garg'

allow-newer: true
extra-deps:
- ghci-8.6.5@sha256:886e52e6ab43b0de39fd5d92d8d1a5d7fac04c0f145c62b39baae04476208bd9
- ghc-boot-8.6.5@sha256:8b608d2f36aad99a37a7d1b70319d43195128de6485b15fa7d4638b2942ce2a2
- git: https://github.com/delanoe/data-time-segment.git
  commit: 10a416b9f6c443866b36479c3441ebb3bcdeb7ef
- git: https://gitlab.iscpif.fr/gargantext/hlcm.git
  commit: 6f0595d2421005837d59151a8b26eee83ebb67b5
- git: https://github.com/delanoe/servant-static-th.git
  commit: 8cb8aaf2962ad44d319fcea48442e4397b3c49e8
- git: https://github.com/delanoe/hstatistics.git
  commit: 90eef7604bb230644c2246eccd094d7bfefcb135
- git: https://github.com/paulrzcz/HSvm.git
  commit: 3fe28b683aba5ddf05e3b5f8eced0bd05c5a29f9
- git: https://github.com/robstewart57/rdf4h.git
  commit: 4fd2edf30c141600ffad6d730cc4c1c08a6dbce4
    #
    # External API connectin to get data
- git: https://gitlab.iscpif.fr/gargantext/crawlers/pubmed.git
  commit: 01a6bf1e79cd5aef8628b240bbd47cb2a0864d5e
- git: https://gitlab.iscpif.fr/gargantext/crawlers/istex.git
  commit: daeae80365250c4bd539f0a65e271f9aa37f731f
- git: https://gitlab.iscpif.fr/gargantext/crawlers/hal.git
  commit: ef9e638c97788df251f50b71fcdd9551b87f12c5
- git: https://gitlab.iscpif.fr/gargantext/crawlers/isidore.git
  commit: 3db385e767d2100d8abe900833c6e7de3ac55e1b
    #
- git: https://gitlab.iscpif.fr/gargantext/patches-class
  commit: 746b4ce0af8f9e600d555ad7e5b2973a940cdad9
#- git: https://github.com/delanoe/servant-job.git
- git: https://github.com/np/servant-job.git
  commit: 8557bfc9472a1b2be0b7bc632c23701ba5f44bf8
- git: https://gitlab.iscpif.fr/gargantext/clustering-louvain.git
  commit: b29040ce741629d61cc63e8ba97e75bf0944979e
- git: https://github.com/np/patches-map
  commit: 8c6f38c4844ead53e664cf9c82ba461715dbe445
- git: https://github.com/delanoe/haskell-opaleye.git  #- opaleye-0.6.7002.0
  commit: 53385de076be09f728a1b58c035a18e9ff9bcfd6
- git: https://github.com/delanoe/hsparql.git
  commit: 308c74b71a1abb0a91546fa57d353131248e3a7f
- KMP-0.1.0.2
- accelerate-1.2.0.1
- aeson-lens-0.5.0.0
- deepseq-th-0.1.0.4
- duckling-0.1.3.0
- full-text-search-0.2.1.4
- fullstop-0.1.4
- haskell-igraph-0.7.1
- hgal-2.0.0.2
- located-base-0.1.1.1
- multiset-0.3.4.1 # stack test
- probable-0.1.3
- rake-0.0.1
- json-stream-0.4.2.4  # Text.Parsers (JSON)
- serialise-0.2.0.0
- servant-flatten-0.2
  #- servant-multipart-0.11.2
- stemmer-0.5.2
- time-units-1.0.0
- validity-0.9.0.0 # patches-{map,class}
- directory-1.3.1.5
- process-1.6.5.1@sha256:77a9afeb676357f67fe5cf1ad79aca0745fb6f7fb96b786d510af08f622643f6,2468
- argon2-1.3.0.1@sha256:e7771caf255929453c7cebfed0809617c51428d1c1b22f207c80b8711b792d78,4592

extra-lib-dirs:
  - /usr/lib
