flags: {}
extra-package-dbs: []
packages:
- .
- '/home/alexandre/local/logiciels/haskell/accelerate/accelerate'

allow-newer: true
extra-deps:
- git: https://github.com/delanoe/data-time-segment.git
  commit: 4e3d57d80e9dfe6624c8eeaa8595fc8fe64d8723
- git: https://gitlab.iscpif.fr/gargantext/hlcm.git
  commit: 6f0595d2421005837d59151a8b26eee83ebb67b5
- git: https://github.com/delanoe/servant-static-th.git
  commit: fff77e79fe94d563ab5cae2609b78c17b5c1f434
- aeson-1.2.4.0
- aeson-lens-0.5.0.0
- duckling-0.1.3.0
- extra-1.5.3
- file-embed-lzma-0
- haskell-src-exts-1.18.2
- http-types-0.12.1
- protolude-0.2
- servant-0.13.0.1
- servant-auth-0.3.1.0
- servant-client-0.13.0.1
- servant-client-core-0.13.0.1
- servant-docs-0.11.2
- servant-multipart-0.11.1
- servant-server-0.13.0.1
- servant-swagger-ui-0.3.0.3.13.2
- servant-swagger-ui-core-0.3
- stemmer-0.5.2
- text-1.2.3.0
- text-show-3.6.2
resolver: lts-11.6
