#!/bin/bash


if git --version;
then 
  echo "git installed, ok"
else
  sudo apt update && sudo apt install -y git
fi

sudo apt update
sudo apt install -y liblzma-dev libpcre3-dev libblas-dev liblapack-dev pkg-config libgsl-dev libbz2-dev postgresql nginx libpq-dev libigraph0-dev

# Phylo management
sudo apt install -y graphviz

sudo apt install -y postgresql-server-dev-11

