#!/bin/bash

sudo apt-get -y remove --purge docker docker-engine docker.io containerd runc


sudo apt-get -y install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"

sudo apt update

sudo apt-get -y install docker-ce docker-ce-cli containerd.io
sudo apt -y install docker-compose

sudo addgroup gargantua docker

